### ISSUE TITLE
Nodding doesn't work with short exposures

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#103]
When doing sky flats with exposure delay of 5 secs, the nodding doesn't seem to work properly - it does not work its way down the text file of offsets, but seems to keep repeating the same (or a subset) of the offsets. Is it because of the short exposure time?

**Comment by vikdhillon** [comment]
Ah - ah the offsets reported in the GTC_Offsetter window relative? If so, then all is ok (just confusing as the numbers in there are different to what the user enters in the text file.)

**Comment by StuartLittlefair** [comment]
Yes - the offsets shown in ```gtc_offsetter``` are relative. Would you like this changed @vikdhillon?
