### ISSUE TITLE
Avoid having to power on when restarting hdriver

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#109]
When having to restart hdriver whilst observing, e.g. if it hangs (which it has done once so far in the past 3 nights), it would be good not to have to hit the power on button to avoid the dark current hit. It is possible to do this in expert mode, but then one has to observe all night in this mode. Is there any way of checking to see if the bias voltages are already on and then not insisting on a power on?

**Comment by StuartLittlefair** [comment]
Hi @vikdhillon - we actually fixed this in April (https://github.com/HiPERCAM/hcam_widgets/commit/66119e7a36aee87ec2203cab684f761c10b792ae)

Even though you still have to click power on, it won't actually power on the clocks if they're already on. this should be visible in the logs, which should read ''clocks already on''
