### ISSUE TITLE
Do not allow binning of more than 2 in overscan or pre-scan mode, in either window or full-frame mode

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#112]
After much head-scratching and testing trying to get arbitrary binning to work with overscan/pre-scan mode in the pipeline, Tom and I have decided that it is not worth the effort! No observer is likely to be negatively affected by this decision. So please could you remove the possibility of doing this entirely from hdriver?

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam_widgets/commit/0c7aabf3ff0a73dfc5b484d4bc461a7d4a6a1d3f
