### ISSUE TITLE
Stephen Hawking "exposure finished" alarm should not work on pressing stop button

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#113]
I think it might be better if the "exposure finished" alarm (Stephen Hawking voice) should only activate when a fixed number of exposures are entered by the user and they finish. It gets annoying every time the alarm sounds when you click "STOP", and there is no need for it as the user knows the exposure has finished.

**Comment by StuartLittlefair** [comment]
Should be fixed by 

https://github.com/HiPERCAM/hcam_widgets/commit/f9423703d054c07ae4a3b51511f8c5b81510465e

and 

https://github.com/HiPERCAM/hcam_widgets/commit/e084493a8ff55490a07fb328239db6b289cb982b
