### ISSUE TITLE
Option in hdriver required to turn rtplot server on and off

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#116]
It would be useful to have a menu option in hdriver which allows you to turn the rtplot server on and off. (What exactly does the "Server on" button do?)

**Comment by vikdhillon** [comment]
On second thoughts, it would be ok to have the rtplot server on all of the time, assuming it works without problems - we need to test this more thoroughly as we had an hdriver hang and were not sure if this was because of the rtplot server had just been turned on.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/229613f61f43f9de0536d4cd92fd51097941bea2
