### ISSUE TITLE
hdriver hangs in drift mode

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#122]
I think we've seen this one before, but I've found a way round it without having to shut down hdriver, etc:

Starting a drift mode run hangs hdriver until it times out. Trouble is, the ESO GUI then reports it is in error. It is possible to recover from this quite cleanly by selecting "ONLINE" from the "Online" drop-down menu bar at the top of the ESO GUI, and then clicking "Start" on hdriver again (twice, I believe).

**Comment by StuartLittlefair** [comment]
Yes - that should work. Not this is not really an issue with hdriver; instead it's an issue with the ESO s/w that changing readout mode to drift mode can either hang for a long time, or cause an error state in the ESO GUI.

**Comment by StuartLittlefair** [comment]
@vikdhillon did you have any problems with this in October? I think we fixed this with the changes we made to the acquisition task parameters in #127

**Comment by vikdhillon** [comment]
No, we never had a drift mode hang during the (early) October run. We
didn't use drift mode at all during the late October run.
So it looks like this is fixed now?

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---
