### ISSUE TITLE
Maximum value of NSKIPS

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#125]
Is there a reason that hdriver limits the maximum number of NSKIPS to 20? We've got a really red exoplanet host star tonight and were thinking of doing even more NSKIPS than this in u.

**Comment by StuartLittlefair** [comment]
None at all - it needed a max and I thought 20 was large enough to never get used! I'll set it to 50

**Comment by StuartLittlefair** [comment]
fixed in 
https://github.com/HiPERCAM/hcam_widgets/commit/9f4b5e3232603898ec55e6ad8c00d3733e8d8c7d

please re-install hcam_widgets to get the latest version

**Comment by vikdhillon** [comment]
Great - thanks! Guo would like 120, and Steven has used 100 with ULTRACAM in the past, apparently, so how about making the maximum 200?

**Comment by StuartLittlefair** [comment]
120!! Gosh. Done
