### ISSUE TITLE
json file saved by hdriver has superfluous contents

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#131]
I just looked at one of the json files saved by hdriver on the rack PC. The contents are listed below. This was saved during October 2018 for one of Alberto Rebassa's programmes, yet it has a whole load of entries from one of Antonio de Ugarte Postigo in it (under the gtc_headers block) from 2017B. I'm pretty sure these entries are superfluous and shouldn't be in there - any idea why they have been written?

{
    "appdata": {
        "app": "FullFrame",
        "clear": 0,
        "dummy_out": 1,
        "dwell": 4.8,
        "exptime": 5.01374208,
        "fast_clks": 0,
        "led_flsh": 0,
        "multipliers": [
            3,
            1,
            1,
            1,
            1
        ],
        "numexp": 0,
        "oscan": 0,
        "oscany": 0,
        "readout": "Slow",
        "xbin": 4,
        "ybin": 4
    },
    "gps_attached": 1,
    "gtc_headers": {
        "AIRMASS": "1.40244",
        "AZIMUTH": "157.352",
        "DEC": "+04:48:35.600",
        "DECDEG": "4.809889",
        "DEWPOINT": "4.0568",
        "DOME_AZ": "161.244",
        "ELEVAT": "45.4315",
        "FRAME": "FK5",
        "GTCOBID": "0006",
        "GTCPRGID": "GTCMULTIPLE2I-17B",
        "HEIGHT": "2348",
        "HUMIDITY": "70.85",
        "HUMIN": "63.0",
        "HUMOUT": "70.8",
        "INSTRPA": "264.64",
        "INSTRUME": "HIPERCAM",
        "LATITUDE": "28.762000",
        "LONGITUD": "17.877639",
        "LST": "+21:17:11.279",
        "M2RX": "0.00102059",
        "M2RY": "-0.000548858",
        "M2UX": "2.16582",
        "M2UY": "4.0463",
        "M2UZ": "-1.67551",
        "OBJECT": "GRB171205A",
        "OBSERVAT": "ORM",
        "OBSERVER": "SA",
        "PARANG": "-52.8741",
        "PI": "adeugarte",
        "POX": "0",
        "POY": "0",
        "PRESSURE": "775.121",
        "RA": "+23:55:26.635",
        "RADEG": "358.86098",
        "ROTATOR": "137.717",
        "SLATEL": "LP10.0",
        "TAMBIENT": "9.1053",
        "TELESCOP": "GTC",
        "TELFOCUS": "0",
        "T_PRIM": "8.425",
        "T_TUBE": "9.71293",
        "WINDDIRE": "7",
        "WINDSPEE": "0.792233"
    },
    "hardware": {
        "ccd1flow": 1.29,
        "ccd1temp": -89.9,
        "ccd1vac": 0.00135,
        "ccd2flow": 1.1,
        "ccd2temp": -87.7,
        "ccd2vac": 0.00301,
        "ccd3flow": 1.29,
        "ccd3temp": -87.4,
        "ccd3vac": -99,
        "ccd4flow": 1.16,
        "ccd4temp": -90.0,
        "ccd4vac": 0.00155,
        "ccd5flow": 1.29,
        "ccd5temp": -90.0,
        "ccd5vac": -99,
        "fpslide": 80.00024789663439
    },
    "tcs": {
        "DEC": "+4:48:36",
        "RA": "23:55:27",
        "alt": 45.4,
        "az": 114.6,
        "foc": -1.68,
        "mdist": 147.23,
        "pa": 264.64,
        "secz": 1.41,
        "tel": "GTC"
    },
    "user": {
        "ID": "GTC21-18B",
        "OBID": "0001",
        "Observers": "vsd,sgp,prg",
        "PI": "arebassa",
        "comment": "",
        "filters": "us,gs,rs,is,zs",
        "flags": "data",
        "target": "SDSS J235524.29+044855.7"
    }
}

**Comment by StuartLittlefair** [comment]
It's to do with FITS headers. Any FITS header items we want to set at run start, need to be in the JSON that gets posted to the ESO s/w.

Therefore, when we create a JSON representation of an OB (either to save to disc, or post to the servers), we have to add a whole bunch-of-stuff from the GTC telescope server, so that the GTC can have the FITS headers they want. 

The stuff in this JSON file is from whatever the telescope was currently doing when you clicked "Save". I agree this is not what we want, so I'm changing ```hcam_widgets``` so this stuff is not added when you click "Save", only on "Start".

A knock on effect is that saved JSON files will not have the ```hardware``` or ```tcs``` sections in them.
