### ISSUE TITLE
Hour angle has the wrong sign in hdriver

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam-drivers#151]
Example RA=19:20, LST=15:20 gives HA = +3 hours whereas it should be -3 (rising). Caused me to screw up acquiring a target as I thought it was near the meridian whereas it was quite low.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam_widgets/commit/8b5ae59fe93cec558f60b418844f549171ebd51b

new version installed on rack
