### ISSUE TITLE
Start exposure button incorrectly enabled when run already started

### ISSUE THREAD

**Issue by SGParsons** [HiPERCAM/hcam-drivers#158]
When a run is going it is possible to select the run type from the pulldown menu (e.g. Bias) and this will enable the start button to be pressed (i.e. it changed from greyed out to green).

It's unclear what exactly the camera does at this point, but one side effect is that the computer will continuously broadcast the "exposure finished" sound 

We were logged in as level 0 expert.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/5ea7f9dcd4031757950fb3808e35cc9bbba5477b
