### ISSUE TITLE
Option to remove the "Are you sure you want to start a run?" window

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#69]
Would it be possible to have an option to remove the "Are you sure you want to start a run?" window, which is a little annoying coming on top of having to select the data type prior to hitting start. We don't have this with ULTRACAM and it doesn't really matter if someone makes a mistake and starts a run by accident, does it?

**Comment by StuartLittlefair** [comment]
Not really;

I could just remove it entirely if you orefer

**Comment by vikdhillon** [comment]
Yes, we're all agreed here that we'd like it removed!

**Comment by StuartLittlefair** [comment]
Fixed. I’ll get onto the others tomorrow.
