### ISSUE TITLE
START_HICAM doesn't always open the HServer window

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#74]
On first typing start_hicam, it doesn't always open the hserver window, saying that it is already running. But it isn't (via checking with ps). On typing start_hicam again, it always opens the hserver window.

**Comment by StuartLittlefair** [comment]
Can you tell me what the output of `ps ax | grep hserver | wc -l` is when the `hserver` isn't running?

**Comment by vikdhillon** [comment]
hipercam{observer}1: ps ax | grep hserver | wc -l
1
hipercam{observer}2:

**Comment by StuartLittlefair** [comment]
Odd - that's what it should be. I can't get to the bottom of this just yet, but I've added some debug info to ```start_hicam``` that will allow me to make progress

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/9bfb728ae28ac83d0713ca2d7539a732bb48acc8
