### ISSUE TITLE
Telescope name doesn't appear in file headers

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#75]
The telescope name is selected by the user in the GUI, but doesn't seem to appear in the FITS headers. This would be useful to prevent confusion when we start moving between the WHT and GTC.

**Comment by StuartLittlefair** [comment]
There's an ORIGIN header item which I think is fixed to ESO-PARANAL. I'll see if I can change it.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/5f4189574fd833cd95e91e100c085a70e1d37ba8

put into header item TELESCOP
