### ISSUE TITLE
Target name needs setting to FLAT,] 

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hcam-drivers#78]

**Comment by vikdhillon** [comment]
When selecting the FLAT data type, the target name remains unchanged, which means it is often set to "Bias" as this is usually the name of the preceding run.

**Comment by vikdhillon** [comment]
I've just realised the same thing happens with the BIAS data type as well.

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/8886d6b7e5a6be44c1ae2c68145cb5df6f714e15
