### ISSUE TITLE
Target names are all WASP-104

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam-drivers#98]
All the target names in the FITS header seem to be recorded as WASP-104

**Comment by StuartLittlefair** [comment]
Maddening @trmrsh! This is because the target name set in the telescope server is taking precedence. I had thought I had fixed this so that it did not, but obviously that fix is not working.

**Comment by StuartLittlefair** [comment]
Maybe worth asking why the TO has not entered a target name, or has the wrong target name....

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/f8fa413e569b50a40c102df0c04aff76a15f60ed

**Comment by trmrsh** [comment]
Similar issue perhaps with observer (set to 'SA') and PI (set to 'gchen')

**Comment by StuartLittlefair** [comment]
Yes - this is now fixed see above

**Comment by trmrsh** [comment]
but I need to update hcam-drivers on the drpc do I?

**Comment by StuartLittlefair** [comment]
no, i've just updated the s/w on the rack, so stopping and re-starting the GUI and hserver *should* fix this
