### ISSUE TITLE
gtc_tweak_pointing

### ISSUE THREAD

**Issue by trmrsh** [HiPERCAM/hcam-drivers#99]
Hi Stu, please set paOff = 76.97 in gtc_tweak_pointing and install,

cheers,

tom

**Comment by StuartLittlefair** [comment]
In hfinder too presumably? All the other parameters are ok, even rotator Center?

**Comment by StuartLittlefair** [comment]
Done. fixed in https://github.com/HiPERCAM/hcam-drivers/commit/4c1f46f8f25deb383b52ac1bc793f9c8d86752cd
